logging.level.org.springframework.ai=DEBUG
#logging.level.org.springframework.ai.mcp=DEBUG
#logging.level.org.springframework.ai.tools=DEBUG
logging.level.io.modelcontextprotocol=DEBUG

#debug=true
# https://docs.spring.io/spring-boot/reference/using/devtools.html
spring.devtools.restart.enabled=false
spring.devtools.restart.log-condition-evaluation-delta=true
#spring.devtools.livereload.enabled=true